<?php

// Generated e107 Plugin Admin Area 

require_once('../../class2.php');
if (!getperms('P')) 
{
	e107::redirect('admin');
	exit;
}

e107::lan('yandex_metrica',true);


class yandex_metrica_adminArea extends e_admin_dispatcher
{

	protected $modes = array(	
	
		'main'	=> array(
			'controller' 	=> 'yandex_metrica_ui',
			'path' 			=> null,
			'ui' 			=> 'yandex_metrica_form_ui',
			'uipath' 		=> null
		),
 	

	);	
	
	
	protected $adminMenu = array(
			
		'main/prefs' 		=> array('caption'=> LAN_PREFS, 'perm' => 'P'),	
		'main/gdpr' 		=> array('caption'=> 'GDPR info', 'perm' => 'P'),
		// 'main/div0'      => array('divider'=> true),
		// 'main/custom'		=> array('caption'=> 'Custom Page', 'perm' => 'P'),
		
	);

	protected $adminMenuAliases = array(
		'main/edit'	=> 'main/list'				
	);	
	
	protected $menuTitle = 'Yandex Metrica';
}




				
class yandex_metrica_ui extends e_admin_ui
{
			
		protected $pluginTitle		= 'Yandex Metrica';
		protected $pluginName		= 'yandex_metrica';
	//	protected $eventName		= 'yandex_metrica-'; // remove comment to enable event triggers in admin. 		
		protected $table			= '';
		protected $pid				= '';
		protected $perPage			= 10; 
		protected $batchDelete		= true;
		protected $batchExport     = true;
		protected $batchCopy		= true;	
		protected $listOrder		= ' DESC';
	
		protected $fields 		= NULL;		
		
		protected $fieldpref = array();
		
                                                                                 
	//	protected $preftabs        = array('General', 'Other' );
		protected $prefs = array(
			 	'yandex_metrika_active'		=> array('title'=> 'Active', 'tab'=>0, 'type'=>'boolean', 'data' => 'str', 'help'=>'Is plugin active?'),
				'yandex_metrika_id'		    => array('title'=> LAN_PLUGIN_YANDEX_METRICA_003, 'tab'=>0, 'type'=>'text', 'data' => 'str', 'help'=>'',
				'writeParms'=>array(
				'placeholder'=>'99999999', 
				'pattern' => '[0-9]+',
				'post' => "<div class='bg-info' style='color: white;padding: 5px;'> ID of your site. You may find it in the code generated by metrika. </div>"),
			 ),
 			'yandex_metrika_footer'		=> array('title'=> LAN_PLUGIN_YANDEX_METRICA_005, 'tab'=>0, 'type' => 'boolean',
				'data' => 'str', 'help'=>'',
		    'writeParms' => array(
		        'enabled' => 'Footer', 'disabled' => 'Header',
		    ),
		    ), 
		    
			'yandex_metrika_script' => array(
				'title' => 'Code',
				'type' => 'textarea',
				'data' => 'str',
				'width' => 'auto',
				'help' => '',
				'readParms' => array() ,
				 'writeParms' => array(
					'size' => 'block-level',
					'post' => "<div class='bg-info' style='color: white;padding: 5px;'>Insert full generated code from yandex. The rest of prefs are ignored then.
					You should use option Without linebreaks before generating your snippets. <span class='bg-warning'> Do not insert  comment parts. The code has to start with script tag. </span></div>
          <hr>
					<div class='bg-danger' style='color: white;padding: 5px;'>All options bellow are ignored if you directly insert the code snippet.</div>"
			 	),
				'class' => 'left',
				'thclass' => 'left',
			) ,			   		
			   		
			   		

		    'yandex_metrika_clickmap'  => array('title'=> 'Collect data for a click map?', 'tab'=>0, 'type' => 'boolean',
				'data' => 'str', 'help'=>'',
		    'writeParms' => array(		    
		        'post' => "<div class='bg-info' style='color: white;padding: 5px;'>The click map measures and displays statistics for clicks on your site. WARNING. You need to change class2.php file and comment
						X-Frame-Options. And you can't use Adblock on Click map page. More info: https://yandex.com/support/metrica/behavior/click-map.html </div>"
		    ),
		     
		   ),  
			 
		    'yandex_metrika_trackLinks'  => array('title'=> 'Collect data for external link tracking?', 'tab'=>0, 'type' => 'boolean',
				'data' => 'str', 'help'=>'',
		    'writeParms' => array(
		        'post' => "<div class='bg-info' style='color: white;padding: 5px;'> Track Links, social sharing, file requests...</div>"
		     ),
		     ),
		     
		    'yandex_metrika_accurateTrackBounce'  => array('title'=> 'Bounce', 'tab'=>0, 'type' => 'boolean',
				'data' => 'str', 'help'=>'',
		    'writeParms' => array(
		        'post' => "<div class='bg-info' style='color: white;padding: 5px;'> Bounce mean visitor of the page where on it less than 15 seconds </div>"
		     ),
		     ),	
				 
		    'yandex_metrika_webvisor'  => array('title'=> 'Session Replay, scroll map, form analysis (Webvisor)', 'tab'=>0, 'type' => 'boolean',
				'data' => 'str', 'help'=>'',
		    'writeParms' => array(
		        'post' => "<div class='bg-info' style='color: white;padding: 5px;'>Records and Analysis of the site visitors. 
						When you enable Session Replay, you agree to follow section 15 in the Yandex.Metrica Terms of Use. 
						Session Replay records the actions of site users, including the contents of form fields.
					  Data in confidential fields is automatically replaced with asterisks <i>[Confirmed]</i>. 
						You can disable the recording of form fields in the Session Replay settings. </div>"
		     ),
		     ),				         
		);         

	
		public function init()
		{
			// Set drop-down values (if any). 
	
		}

		
		// ------- Customize Create --------
		
		public function beforeCreate($new_data,$old_data)
		{
			return $new_data;
		}
	
		public function afterCreate($new_data, $old_data, $id)
		{
			// do something
		}

		public function onCreateError($new_data, $old_data)
		{
			// do something		
		}		
		
		
		// ------- Customize Update --------
		
		public function beforeUpdate($new_data, $old_data, $id)
		{
			return $new_data;
		}

		public function afterUpdate($new_data, $old_data, $id)
		{
			// do something	
		}
		
		public function onUpdateError($new_data, $old_data, $id)
		{
			// do something		
		}		
		
		// left-panel help menu area. 
		public function renderHelp()
		{
			$caption = LAN_HELP;
			$text = "<a href='http://help.yandex.com/metrika/' target='_blank'>More about Yandex Metrika</a>";

			return array('caption'=>$caption,'text'=> $text);

		}
			
 	
		// optional - a custom page.  
		public function gdprPage()
		{
			$text = '<h2>GDPR compliance</h2><br>';
			$text .= '<b>Info for your private policy:</b><br> This site uses the Yandex.Metrica web analytics service provided by the company Yandex Oy Limited Company - Moreenikatu 6, 04600 Mantsala, Finland.';
			$text .= '<br><br><b>Related links:</b>';
			$text .= "<ul>";
			$text .= "<li><a href='https://yandex.com/support/metrica/general/gdpr.html' target='_blank'>https://yandex.com/support/metrica/general/gdpr.html</a></li>";
			$text .= "<li><a href='https://metrica.yandex.com/about/info/gdpr' target='_blank'>https://metrica.yandex.com/about/info/gdpr</a></li>";
			$text .= "<li><a href='https://yandex.com/legal/metrica_agreement/' target='_blank'>https://yandex.com/legal/metrica_agreement/</a></li>";
			$text .= "<ul>";
			
 
			return $text;
			
		}
 
}
				


class yandex_metrica_form_ui extends e_admin_form_ui
{

}		
		
		
new yandex_metrica_adminArea();

require_once(e_ADMIN."auth.php");
e107::getAdminUI()->runPage();

require_once(e_ADMIN."footer.php");
exit;

?>